### ISSUE TITLE
Smoother Uninstall

### ISSUE THREAD

**Issue by brianegan** [xdrop/night-owl-jetbrains#10]
Hey hey :)

I tried this plugin out, but I decided I liked my own customized Material UI theme and wanted to go back. However, when I uninstalled the plugin, my previous settings were not restored properly. For example, my color scheme settings for Braces are being completely ignored, and I'm stuck with the colors provided by this theme.

In addition, I've lost my run / debug bar as well, which is really crucial for my workflow, and even after restoring the settings for menus it won't  reappear.

Not sure what happened, but it would be great if this plugin had a better story for uninstalling! At this point, I simply had to wipe out my Intellij settings directory entirely and started from scratch. Was a bit of a bummer / lost a bit of time on this one.

Thanks for any help / improvements in this area!

Update: Had a quick look at the code. Overall, I think it might be cool if this plugin didn't disable things like the navigation bar, status bar, etc... I feel like it should provide the Night Owl color scheme, and the user should remain in control of what's shown. Was a big reason I uninstalled in the first place -- I wanted a new color scheme, similar to material UI, but I had specifically chosen my own layout that worked for me and was surprised this plugin changed all of that without warning.

**Comment by xdrop** [comment]
Sure, sounds like a good idea! 

It could maybe prompt on if you wanted the settings changed or not the first time you install it. The plan for it anyway was to provide an "out-of-the-box" experience to what the screenshot was, but I understand that changing it for users without asking might be a bit too intrusive.

I'll try and get that in for the next release, thanks!

**Comment by brianegan** [comment]
Cool, thanks :)

**Comment by xdrop** [comment]
Closed in 37a7d7dbb12e003f88496866c1efb7537c2f2d56
