### ISSUE TITLE
Make the javascript keywords exportable

### ISSUE THREAD

**Issue by mallowigi** [xdrop/night-owl-jetbrains#13]
Good job with the Night Owl color scheme section! However if possible, can you change the section name to "Javascript - extended" (and more importantly, if you're planning on adding other custom highlightings, other languages will be added here) or better, make it a separate plugin so we can all base ourselves on it?

Thanks :)

**Comment by xdrop** [comment]
Good point, I will rename it 👍

And yes could separate it as a plugin once I add a few more 🙂

**Comment by mallowigi** [comment]
Oh and maybe you should make it so it inherits from Javascript keywords instead of taking the default gray value
