### ISSUE TITLE
Downloading just the color scheme?

### ISSUE THREAD

**Issue by Jarzka** [xdrop/night-owl-jetbrains#14]
Hi

Is it possible to download just the code editor theme as JAR file?

I think I don't like that the whole IDE theme changes with this plugin. I noticed that if I uninstall the plugin, the IDE returns to its old default look, but the code editor theme is still there to be used. This how I like it to be and I would like that just the code editor theme could be downloaded.

You could upload it, for example here: http://color-themes.com/?view=index

**Comment by xdrop** [comment]
Maintaining and updating the theme on that website is not feasible or ideal. The best I can do for now is publish a jar on the releases page with the color scheme settings only.

**Comment by xdrop** [comment]
Added as part of release now: 
https://github.com/xdrop/night-owl-jetbrains/releases/download/1.3.1/night-owl-color-scheme-only-1.3.1.jar

Note that this will not have any of the current or future extended highlighting features, nor it will color the IDE panes which might cause the color scheme to look strange unless the background is changed.
