### ISSUE TITLE
Error highlighting not working in Android Studio

### ISSUE THREAD

**Issue by amith007** [xdrop/night-owl-jetbrains#15]
Looks like errors are not highlighted when using night owl theme on Android studio.  Please find a screenshot below. 

semicolon is missing at the end of the statement, however this error is not highlighted. 

![image](https://user-images.githubusercontent.com/10078295/43926227-9d0ae3e2-9bf7-11e8-888a-183ccacba41d.png)

**Details**
 Android Studio 3.2 Beta 5
Build #AI-181.5281.24.32.4913314, built on July 25, 2018
JRE: 1.8.0_152-release-1136-b04 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

Night Owl Theme version: Version: 1.3.0-2018.1

**Comment by xdrop** [comment]
Thanks for reporting. I'll have a look and push an update fixing this soon.
