### ISSUE TITLE
VCS line status

### ISSUE THREAD

**Issue by edvasqueza** [xdrop/night-owl-jetbrains#16]
Hello, I noticed that VCS line status are not configured in the color schemes.

![image](https://user-images.githubusercontent.com/855077/43964889-d409025e-9c8b-11e8-9393-e8513b64508f.png)

Night Owl Theme: 1.3.1
Pycharm: 2018.2.1 Pro

**Comment by xdrop** [comment]
Thanks for reporting. Will add on next release.

**Comment by 0x346e3730** [comment]
I'm having the same problem even after the update, I now see the color in the settings but I can't still see the git status in the gutter.
![vcs](https://user-images.githubusercontent.com/28731165/45281261-983e7b00-b4d7-11e8-9a0b-955fb1e4a14b.png)
As you can see at the right of the screen, left to the scrollbar, the whole "phpmyadmin" part is new yet nothing appears on the gutter. Same problem on two different PCs both running Ubuntu 18.04.

**Comment by xdrop** [comment]
@GrosTon1 Can you check if **Settings>Editor>General>Highlight modified lines in gutter** is enabled?

**Comment by 0x346e3730** [comment]
@xdrop It was indeed unchecked, thank you for your answer. Is it possible to check it by default with themes ? I would be happy do to a PR to correct this

**Comment by xdrop** [comment]
@GrosTon1 That option only gets changed if you chose to accept the *recommended* set of settings during the installation of the plugin.  

Now whether it should be part of the recommended settings or not is a different story. As I'm trying to match the experience of the VS code theme as much as possible, I had it left as disabled (and personally find it distracting while coding). I am however fine to turn it on as part of the recommended if the majority of people want it on.

**Comment by 0x346e3730** [comment]
Then as night owl is an adapation of the VSCode theme, I think it should be added in README but not added in recommended settings as they are meant to be the same as VSCode. What do you think about that ? Maybe a category of default settings in JetBrains IDEs that are "disabled" by Night Owl.
