### ISSUE TITLE
Not compatible with the new EAP release

### ISSUE THREAD

**Issue by Arelav** [xdrop/night-owl-jetbrains#19]
Can't be found and installed from marketplace page in EAP release and also has the message about negative compatibility with this version of IDE when trying to install plugin from disk.

```
WebStorm 2018.3 EAP
Build #WS-183.3795.15, built on October 17, 2018
WebStorm EAP User
Expiration date: November 16, 2018
JRE: 1.8.0_152-release-1343-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

**Comment by xdrop** [comment]
Just released for 2018.3 EAP. Should be available within a few days once approved.
