### ISSUE TITLE
About install rainbow brackets

### ISSUE THREAD

**Issue by izhangzhihao** [xdrop/night-owl-jetbrains#2]
Just curious about [this distribution](https://github.com/xdrop/night-owl-jetbrains/blob/master/rainbow-brackets.zip), why not just download from https://plugins.jetbrains.com? is it build by yourself? did you made any changes of the code?

By the way, this is awesome project, just wonder if I can use your screenshots in [here](https://github.com/izhangzhihao/intellij-rainbow-brackets#screenshots).

**Comment by xdrop** [comment]
Ah, I didn't actually realise I could install it all I could see was this which confused me

![Image](https://i.imgur.com/v9xUHvo.png)

Seeing that it can be installed from the within the IDE this makes the installation a lot simpler, thanks! 😄 I've updated it now.

And yeah you are welcome to use the screenshots, thanks for your awesome work on the plugin! 👏

**Comment by izhangzhihao** [comment]
About the installation, I have a idea:

Create a new plugin which depends on Material Theme UI and Rainbow Brackets both, and you could override the settings of Material Theme UI and Rainbow Brackets as well as intellij build-in settings, and all done.

**Comment by izhangzhihao** [comment]
Sample code [here](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/IC-2017.2/src/main/kotlin/com/github/izhangzhihao/rainbow/brackets/component/RainbowComponent.kt#L23-L31).

**Comment by xdrop** [comment]
@izhangzhihao Good idea, I didn't know you can depend and invoke methods on other plugins. In fact if we go that route we can leverage the [API](https://github.com/ChrisRM/material-theme-jetbrains/blob/7c9cec99b1e9abb6ba40718921f8e4bf1d7c6cf8/src/main/java/com/chrisrm/idea/MTThemeManager.java#L255) of Material Theme UI to import the theme as well.

I'll try and do this when I get the time, thanks 🙂

**Comment by izhangzhihao** [comment]
See #3
