### ISSUE TITLE
No visual guides appear

### ISSUE THREAD

**Issue by samwaterbury** [xdrop/night-owl-jetbrains#22]
In **Preferences -> Editor -> Code Style** it is possible to set visual guides which display a vertical bar indicating the specified column width. However, they do not appear with the Night Owl theme. Only the guide for the **Hard wrap at** setting appears.

Here are my settings:
<img width="1118" alt="screen shot 2019-01-06 at 8 20 52 pm" src="https://user-images.githubusercontent.com/30158870/50745578-9e780600-11f0-11e9-8e12-3c5a74fef367.png">
This is what it looks like with a standard Material theme selected:

<img width="932" alt="screen shot 2019-01-06 at 8 19 34 pm" src="https://user-images.githubusercontent.com/30158870/50745613-cebfa480-11f0-11e9-9fd4-cbc243216adb.png">

This is what it looks like with Night Owl:

<img width="967" alt="screen shot 2019-01-06 at 8 20 08 pm" src="https://user-images.githubusercontent.com/30158870/50745614-d2532b80-11f0-11e9-887c-3cff481634fb.png">

I am not very familiar with writing themes for Jetbrains IDEs, however it seems to me that this is being caused because the color for these visual guides is not specified. For example, line 77 in `src/main/resources/colors/NightOwl.xml` is:

```xml
        <option name="VISUAL_INDENT_GUIDE" value=""/>
```

On the other hand, the hard wrap guide _does_ work because its color is properly specified on line 55:

```xml
        <option name="INDENT_GUIDE" value="34324a"/>
```

This issue exists in:
* `src/main/resources/colors/NightOwlCarbonNoItalic.xml`
* `src/main/resources/colors/NightOwl.xml`
* `src/main/resources/colors/NightOwlCarbon.xml`
* `src/main/resources/colors/NightOwlNoItalic.xml`

If there's a reason for this I'm unaware of, let me know.

**Comment by xdrop** [comment]
Thanks, should be an easy fix. Will update today

**Comment by samwaterbury** [comment]
Awesome! Thanks for your work on this theme, it's my favorite theme for JetBrains IDES.

**Comment by samwaterbury** [comment]
Hmmm, it seems my proposed solution did not work, the visual guides still don't show up by default. 

However, I just found out I am able to make them appear by going to **Preferences -> Editor -> Color Scheme -> General** and filling in a color for **Editor -> Guides -> Visual Guides -> Foreground**. So while I still have no idea why they didn't show up, the issue is resolved for me anyways. 👍
