### ISSUE TITLE
Information about the layout changes 

### ISSUE THREAD

**Issue by muescha** [xdrop/night-owl-jetbrains#25]
## Expected Behaviour

- What is the behaviour you were _expecting_

it should inform which Toolbars / Outlines it deactivate or change 

- What is the feature you want _added_

more information about this topic in this places:

  1.   theme description while installing form marketplace
  2.   more information in the diaogbox after installing the plugin and setting up
  3.   in README in this github repository
  4.   more info in the plugin settings dialog ( in settings / other settings / NIght Owl)

## Current Behaviour

- What is the behaviour you are _currently experiencing_

i get a dialogbox where i can apply some changes where i think i have never the chance to revert it do default, because i don't know which changes are made. i pressed the cancel button to avoid confusion of missing parts

- What is the plugin _missing_ right now
n/a

- Add any _screenshots_ showing the issue
n/a

- Add any _stacktraces_ with error messages
n/a

## System details

- Provide IDE and OS versions
- Provide plugin version

**Plugin Version:** 1.3.2

```
IntelliJ IDEA 2018.3.4 (Ultimate Edition)
Build #IU-183.5429.30, built on January 29, 2019
Licensed to [... removed ...]
Subscription is active until August 1, 2019
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

**Comment by xdrop** [comment]
Thanks, I'll work on improving them in the next release.

**Comment by muescha** [comment]
thx -🤔 i can not find the new warning message in some code commit up to 1.4.0

**Comment by xdrop** [comment]
It's here https://github.com/xdrop/night-owl-jetbrains/blob/a557aa683e1699ec3beba87a7e849ab4dcdb52aa/src/main/kotlin/me/xdrop/nightowl/dialog/SetSettingsDialog.form#L15

But most importantly there is an option to reset each individual setting at the settings page now.

**Comment by muescha** [comment]
oh yes thx - it was hidden on long line ...

**Comment by tosin12800** [comment]
when i installed it, i lost my run button on the top right of my terminal. how would i get that whole taskbar back

**Comment by xdrop** [comment]
@tosin12800 Go in Settings (Preferences) > Other Settings > Night Owl, you should find the revert toolbar setting there.
