### ISSUE TITLE
Disable Select border

### ISSUE THREAD

**Issue by vikas5914** [xdrop/night-owl-jetbrains#35]
Is there any way to remove the border sawn in the screenshot. 

![Screenshot_2](https://user-images.githubusercontent.com/7912297/60740934-3af34900-9f85-11e9-9284-5cb1cc1ae7d1.png)

## System details

- Provide IDE and OS versions
PhpStrom 2019.1

- Plugin Version:** 1.3.2
1.5.2

**Comment by mallowigi** [comment]
Color Scheme > General > Identifier under caret
