### ISSUE TITLE
Incompatible with Webstorm 2019.2

### ISSUE THREAD

**Issue by thebuilder** [xdrop/night-owl-jetbrains#36]
The new version **2019.2** of Webstorm is now officially released, and it unfortunately marks  the night owl theme as incompatible.

Is there actually a breaking change, or is it just a question of bumping a version number? 🙂
Is there anything that can be done to "automate" this in the future?

Thanks!

**Comment by fimion** [comment]
Pycharm 2019.2 also isn't compatible.

**Comment by xdrop** [comment]
Released 1.5.3 to fix this. It will be available shortly.

Unfortunately releasing plugins doesn't seem to allow for automation at the moment, but might consider skipping version targets in the future.

**Comment by thebuilder** [comment]
Sweet! 🤘
But 10 hours later, and it doesn't seem to have been published yet? 🤔
https://plugins.jetbrains.com/plugin/10936-night-owl-theme/ is still at **1.5.2**.
