### ISSUE TITLE
Incompatible with WebStorm 2019.3

### ISSUE THREAD

**Issue by jogoodma** [xdrop/night-owl-jetbrains#38]
Night Owl incompatible with the newly released WebStorm 2019.3.  Likely the same issue as #36 .

Thanks!

**Comment by swjjxyxty** [comment]
Incompatible with IDEA 2019.3。

When to release a new version?

**Comment by xdrop** [comment]
I will be releasing an update today.

**Comment by nicholasruunu** [comment]
Thank you @xdrop, really love the theme. 👍

**Comment by sharbel93** [comment]
cant wait ... cant code without this theme.

**Comment by xdrop** [comment]
New version released, will be available once approved.
