### ISSUE TITLE
[BUG] Settings reset every time you start up WebStorm

### ISSUE THREAD

**Issue by RosenTomov** [xdrop/night-owl-jetbrains#4]
These are the ones I've changed:
Settings -> Editor -> General -> Editor Tabs
Tab Limit keeps resetting to 1.

Settings -> Editor -> General -> Appearance
`Show indent guides` keeps getting unchecked.

**Comment by xdrop** [comment]
Thanks for the report!

Unfortunately I inverted the if condition for some reason that triggers the auto configuring.

As a temporary fix you can go to **Settings > Other Settings > Night Owl >Enable Auto-Set Appearance** ( I know this says the opposite thing of what it does)

I'll fix it in the next version and then you can revert back to having it unticked as it should be.

**Comment by xdrop** [comment]
Closed in 674845faaa0d1f279549a18617b0ffabb0254c7a
