### ISSUE TITLE
Incompatible with WebStorm 2020.1

### ISSUE THREAD

**Issue by emnsen** [xdrop/night-owl-jetbrains#42]
The new version 2020.1 of WebStorm is now officially released, and it unfortunately the night owl theme as incompatible.

**Comment by mallowigi** [comment]
If you need a NightOwl theme, my plugin (Material Theme) has one. I don't know the differences with this one since I started from scratch but they should be pretty similar in the meantime

**Comment by emnsen** [comment]
Actually I didn't realize and it seems good, I'll try. Thank you for your suggestion.

**Comment by jryd** [comment]
Incompatible with PHPStorm 2020.1.

@xdrop looking at the last update, is it as simple as just updating the versions it supports?

**Comment by envygeeks** [comment]
@mallowigi there is a huge difference

This theme:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/99763/80698225-c9e6ca00-8a9f-11ea-9a48-dc5c919f0142.png">

Your Theme:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/99763/80698619-5d1fff80-8aa0-11ea-816a-ad50f153c722.png">

I don't think the dark green in your theme is part of the original color scheme.

**Comment by mallowigi** [comment]
I don’t know where does this dark green comes from but it doesn’t look like it comes from my plugin. Make sure you use the provided color schemes with no changes.

**Comment by envygeeks** [comment]
That's the point, this theme supports brackets, your theme doesn't. Brackets is an ideal plugin.

**Comment by envygeeks** [comment]
Actually I reconfigured brackets and got it to match @mallowigi so I'm switching to your theme and upgrading, though it would be nice if you supported brackets out of the box!

**Comment by mallowigi** [comment]
I support brackets out of the box, I just don’t require it.

**Comment by xdrop** [comment]
I have released an update to this plugin for versions 2020.1.

With that being said I am no longer actively using IntelliJ products I can't speak to how well the theme fits the updates. From a quick look I had on 2020 even the default UI looks awful on Mac (no idea what happened with the default fonts and their spacing). If there are issues / need to see further changes I'd be happy to accept contributions but won't be actively trying to fix them.

As a reminder there is a [color-scheme only version ](https://github.com/xdrop/night-owl-jetbrains/releases) that should work across versions. If you're looking for something perhaps more well maintained I would look at the built-in versions of this theme on Material UI shared above.
