### ISSUE TITLE
Incompatible with PHPStorm 2021

### ISSUE THREAD

**Issue by haztakki** [xdrop/night-owl-jetbrains#46]
PHPStorm 2021.1
macOS Big Sur 11.2.3

Love this theme! Just installed it a few days ago, PHPStorm 2021 just got released and it says that the theme is incompatible. Is there a hotfix inbound?

**Comment by haztakki** [comment]
I have created a PR for this, hopefully it is OK. I'm not a Kotlin/Java developer so I just looked how previous versions were supported and followed along.

**Comment by xdrop** [comment]
Hi @HazJ I've just published an update https://plugins.jetbrains.com/plugin/10936-night-owl-theme/versions/stable/117073, it will be available once approved by Jetbrains.

In the meantime if you aren't interested in Material Theme / Rainbow Brackets you can just the color scheme from https://github.com/xdrop/night-owl-jetbrains/releases/tag/1.5.4 (the `jar` file works on all versions)

**Comment by haztakki** [comment]
Ah, I didn't know. Thanks. You can close my PR then.
