### ISSUE TITLE
Support 2021.2

### ISSUE THREAD

**Issue by laike9m** [xdrop/night-owl-jetbrains#49]
## Expected Behaviour

Night Owl Theme to support Jetbrains IDE >= 2021.2

## Current Behaviour

> Plugin 'Night Owl Theme' (version '1.5.8') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is PY-212.5080.64

## System details

**Plugin Version:** 1.5.8

```
PyCharm 2021.2.1 (Professional Edition)
Build #PY-212.5080.64, built on August 25, 2021
Runtime version: 11.0.11+9-b1504.16 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
```

**Comment by laike9m** [comment]
Also, I wonder if it's really necessary to always have an upper bound for IDE version:

https://github.com/xdrop/night-owl-jetbrains/blob/2020.1/build.gradle#L53

```gradle
patchPluginXml {
    changeNotes file("$projectDir/docs/CHANGELOG.html").text
    sinceBuild '211'
    untilBuild '211.*'
}
```

Every time I upgrade the IDE, night owl becomes incompatible. I really love the plugin, but this has been bothering me.

**Comment by xdrop** [comment]
Pushed another update with until set to `215`, that should give at least a couple more releases without needing another review. Should be available once jetbrains approves it.

**Comment by laike9m** [comment]
Thank you!
