### ISSUE TITLE
Compatibility issues with lower version of Rainbow Brackets

### ISSUE THREAD

**Issue by xdrop** [xdrop/night-owl-jetbrains#6]
If someone has already installed an older version Rainbow Brackets (confirmed with 5.8.1) and tries to install this plugin, they get a big exception when they try to restart their IDE about `RainbowifyKotlinFunctionLiteralBracesAndArrow` not being a method of the settings class (since it was introduced in 5.8.2), and disables the plugin requiring another restart.

I was wondering @izhangzhihao if you have any ideas on how to resolve this and make the experience a bit better.

I was thinking instead of using the rainbow brackets settings API itself maybe find out where the location of the XML config file is and then update that file instead. Not sure though, if IntelliJ has any way to find out the directory of that since it varies per operating system.

**Comment by izhangzhihao** [comment]
Using XML as config file is a good idea, but I don't know how to override the XML config file outside of Rainbow Brackets either...

**Comment by xdrop** [comment]
If there was something like a `getIDEPreferencesDirectory()` method provided by IntelliJ then it would be easy to locate the file and replace it. I'll try and have a look around the API and see if I can find anything
