### ISSUE TITLE
Contrast color

### ISSUE THREAD

**Issue by mallowigi** [xdrop/night-owl-jetbrains#7]
Hi,

I've installed your theme but I found out that the Contrast Color is a bit off

![ex](https://user-images.githubusercontent.com/5015756/43355553-d7eb2bec-9266-11e8-84f2-beb91a22cb74.png)

Is this intentional?

**Comment by xdrop** [comment]
Nope, I never turned on Contrast mode to be able to see it and it flew by undetected 😅 

Thanks, I'll change this to a more reasonable choice 😄
